name: 'github-release-notes'
description: 'A GitHub Action to run github-release-notes commands'
author: 'Nicolás Cuellar'
branding:
  icon: 'command'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
